version: '2'
services:
  prometheus:
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - '-config.file=/etc/prometheus/prometheus.yml'
    image: prom/prometheus
spring_prometheus_bridge:
  build: .
  dockerfile: Dockerfile
  container_name: spring-prometheus-bridge
  environment:
    BRIDGE_PORT: 3000
    METRICS_HOST: $METRICS_HOST
    METRICS_PORT: 9001
    METRICS_PATH: metrics
    METRICS_PROTO: https
  ports:
    - "4000:3000"

